### ISSUE TITLE
Making submissions public for large submissions does not work

### ISSUE THREAD

**Issue by goksel** [ICO2S/synbiohub#93] opened 2017-01-20 16:29 UTC
This is an easy fix. When making submissions public,  some data are logged and this process makes it very slow when dealing with large submissions.Eventually, the process cannot be completed.

**Comment by cjmyers** [comment] 2017-01-20 22:47
There was a print in sbolstack-frontend upload of the entire file.  I've removed this.  Please see if this solves the problem for you.  If so, please close this.

**Comment by cjmyers** [comment] 2017-01-22 22:53
Okay found another big debug in sboljs, and removed that too

**Comment by cjmyers** [comment] 2017-02-03 23:15
The problem is in loadRDF from the repository for large files.  This is very inefficient.  Should be replaced with carefully crafted SPARQL queries to grab the SBOL document.

**Comment by cjmyers** [comment] 2017-02-07 12:09
Duplicate

**Closed by cjmyers** 2017-02-07 12:09 UTC
Labels: enhancement
